version: '3.1'

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mybooks
      MYSQL_USER: mybooksUser
      MYSQL_PASSWORD: mybooks2023